---
kind: Service
apiVersion: v1
metadata:
  name: helloworldservicepipelines
spec:
  selector:
    app: hello-pipelines
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 80
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-pipelines
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-pipelines
    spec:
      containers:
        - name: hello-pipelines
          image: vnguyen.azurecr.io/dotnetcore-angular-sample:latest
          ports:
            - containerPort: 80
