---
kind: Service
apiVersion: v1
metadata:
  name: helloworldservice
spec:
  selector:
    app: hello-world
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 80
      nodePort: 30000
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: vnguyen.azurecr.io/dotnetcore-angular-sample:latest
          ports:
            - containerPort: 80
